# Generated by Django 6.1.1 on 2026-10-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='runs_projects',
            field=models.BooleanField(default=False, help_text='Offered when adding a project.'),
        ),
    ]
