# Generated by Django 6.1.1 on 2026-10-08 23:27

from django.db import migrations

def backfill(apps, schema_editor):
    """A company that already has projects obviously runs them."""
    Company = apps.get_model("organization", "Company")
    Project = apps.get_model("organization", "Project")
    ids = list(Project.objects.values_list("company_id", flat=True).distinct())
    Company.objects.filter(pk__in=ids).update(runs_projects=True)

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_runs_projects'),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)
    ]
