# Generated by Django 6.1.1 (dependencies point at the Ivhrms employees and organization migrations)

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='Name (Arabic)')),
                ('cr_number', models.CharField(blank=True, max_length=40, verbose_name='Commercial registration no.')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractors', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.CharField(choices=[('direct', 'Direct employee'), ('contracted', 'Contracted (daily)')], default='direct', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('contractor', models.ForeignKey(blank=True, help_text='Only if a contractor company supplies this worker.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='labor.contractor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='labor_profile', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__employee_no'],
            },
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wage_basis', models.CharField(choices=[('daily', 'Daily wage'), ('monthly', 'Monthly salary')], default='daily', max_length=8)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Per day for a daily wage, per month for a monthly salary.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Rate (BHD)')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Hours beyond this count as overtime.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Standard hours per day')),
                ('overtime_eligible', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='labor.laborprofile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=80, verbose_name='Name (Arabic)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='laborprofile',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='labor.trade'),
        ),
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('company'), name='uniq_contractor_name_per_company', violation_error_message='This company already has a contractor with this name.'),
        ),
        migrations.AddConstraint(
            model_name='laborrate',
            constraint=models.UniqueConstraint(fields=('profile', 'effective_from'), name='uniq_labor_rate_start'),
        ),
        migrations.AddConstraint(
            model_name='laborrate',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('profile',), name='one_open_labor_rate'),
        ),
        migrations.AddConstraint(
            model_name='laborrate',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='labor_rate_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_trade_name', violation_error_message='There is already a trade with this name.'),
        ),
        migrations.AddIndex(
            model_name='laborprofile',
            index=models.Index(fields=['company', 'engagement'], name='labor_labor_company_5ba27e_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborprofile',
            constraint=models.CheckConstraint(condition=models.Q(('engagement', 'contracted'), ('contractor__isnull', True), _connector='OR'), name='direct_labor_has_no_contractor'),
        ),
    ]
