# Generated by Django 6.1.1 (dependencies point at the Ivhrms employees and organization migrations)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('labor', '0001_initial'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='Work order / contract no.')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='organization.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LaborAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Last day on this site. Empty = still there.', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_allocations', to='employees.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.location', verbose_name='Site')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='labor.workorder')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_work_order_code_per_project', violation_error_message='This project already has a work order with this number.'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='work_order_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='laborallocation',
            index=models.Index(fields=['project', 'effective_to'], name='labor_labor_project_dfba9d_idx'),
        ),
        migrations.AddIndex(
            model_name='laborallocation',
            index=models.Index(fields=['location', 'effective_to'], name='labor_labor_locatio_7a42b3_idx'),
        ),
        migrations.AddIndex(
            model_name='laborallocation',
            index=models.Index(fields=['company', 'effective_from'], name='labor_labor_company_c831ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborallocation',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='uniq_allocation_start'),
        ),
        migrations.AddConstraint(
            model_name='laborallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('employee',), name='one_open_allocation_per_worker'),
        ),
        migrations.AddConstraint(
            model_name='laborallocation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='allocation_ends_after_it_starts'),
        ),
    ]
