# Generated by Django 6.1.1 (dependencies point at the Ivhrms employees and organization migrations)

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('labor', '0002_deployment'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('expected_hours', models.DecimalField(decimal_places=2, help_text='What the day expected: standard hours, or half for a half day.', max_digits=4)),
                ('overtime_eligible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_time_entries', to='employees.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='labor.workorder')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
                'indexes': [models.Index(fields=['project', 'date'], name='labor_timee_project_b6fac6_idx'), models.Index(fields=['location', 'date'], name='labor_timee_locatio_f4efa1_idx'), models.Index(fields=['work_order', 'date'], name='labor_timee_work_or_1d04a6_idx'), models.Index(fields=['company', 'status', 'date'], name='labor_timee_company_23cbf0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_time_entry_employee_date'), models.CheckConstraint(condition=models.Q(('hours__gt', 0), ('hours__lte', 24)), name='time_entry_hours_in_range')],
            },
        ),
    ]
