# Generated by Django 6.1.1 (dependencies point at the Ivhrms employees and organization migrations)

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('labor', '0003_timeentry'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_day_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Pay for each overtime hour, as a multiple of the hourly rate.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Normal working day')),
                ('weekly_off_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Weekly off day')),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Public holiday')),
                ('all_hours_on_days_off', models.BooleanField(default=True, help_text='On a weekly off or a holiday, count all hours worked as overtime, not only those beyond the standard day. Payroll must then not also pay that day as a normal working day.', verbose_name='Every hour on a day off is overtime')),
                ('monthly_divisor', models.PositiveSmallIntegerField(default=30, help_text='Turns a monthly salary into a day rate: salary / this number / standard hours = hourly rate.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(31)], verbose_name='Days in a month')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_policies', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('day_kind', models.CharField(choices=[('working', 'Working day'), ('weekly_off', 'Weekly off'), ('holiday', 'Holiday')], max_length=10)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Overtime hours')),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount (BHD)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_overtime_claims', to='employees.employee')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_claim', to='labor.timeentry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_claims', to='labor.workorder')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='labor.overtimepolicy')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.UniqueConstraint(fields=('company', 'effective_from'), name='uniq_overtime_policy_start', violation_error_message='Rules already start on this date. The new rules must start after the current ones.'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('company',), name='one_open_overtime_policy'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='overtime_policy_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='overtimeclaim',
            index=models.Index(fields=['project', 'date'], name='labor_overt_project_cae1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeclaim',
            index=models.Index(fields=['location', 'date'], name='labor_overt_locatio_896839_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeclaim',
            index=models.Index(fields=['company', 'status', 'date'], name='labor_overt_company_1b3918_idx'),
        ),
        migrations.AddConstraint(
            model_name='overtimeclaim',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='overtime_claim_has_hours'),
        ),
    ]
