# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0004_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepolicy',
            name='overtime_applies',
            field=models.BooleanField(default=True, help_text='Untick if the company does not pay overtime. Hours above the standard day are still recorded, but nothing is claimed, and the rates below are ignored.', verbose_name='This company pays overtime'),
        ),
    ]
