# Generated by Django 6.1.1 (dependencies point at the Ivhrms organization migration)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('company', models.ForeignKey(blank=True, help_text='Empty = the default for all companies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'company_id'],
                'constraints': [models.UniqueConstraint(fields=('key', 'company'), name='uniq_setting_key_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('key',), name='uniq_setting_key_default')],
            },
        ),
    ]
