# Generated by Django 6.1.1 on 2026-10-05 15:01

import apps.compliance.schedule
import apps.compliance.storage
import apps.compliance.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='Name (Arabic)')),
                ('applies_to', models.CharField(choices=[('company', 'Company'), ('employee', 'Employee'), ('dependant', 'Dependant')], default='company', max_length=10)),
                ('authority', models.CharField(blank=True, max_length=150, verbose_name='Issuing authority')),
                ('default_validity_months', models.PositiveSmallIntegerField(blank=True, help_text='Used to suggest the next expiry date when renewing.', null=True)),
                ('alert_days', models.JSONField(default=apps.compliance.schedule.default_alert_days, help_text='Days before expiry when alerts are sent. 0 is the expiry day.')),
                ('overdue_repeat_days', models.PositiveSmallIntegerField(default=7, help_text='After expiry, the alert repeats every this many days until it is renewed.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_mandatory', models.BooleanField(default=False, help_text='Every company must hold one. Shown as missing on the dashboard if not.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_name', models.CharField(blank=True, max_length=120)),
                ('number', models.CharField(blank=True, max_length=60)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('agent_name', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, max_length=200, storage=apps.compliance.storage.private_storage, upload_to=apps.compliance.storage.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.compliance.validators.validate_file_size])),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_documents', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='compliance.document')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compliance.documenttype')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RenewalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_tasks', to='compliance.document')),
                ('new_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_task', to='compliance.document')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RenewalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='e.g. "CR renewal fee"', max_length=120)),
                ('paid_on', models.DateField()),
                ('government_fee', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fine', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card', 'Card / online'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('receipt', models.FileField(blank=True, max_length=200, storage=apps.compliance.storage.private_storage, upload_to=apps.compliance.storage.receipt_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.compliance.validators.validate_file_size])),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='compliance.renewaltask')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.SmallIntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='compliance.document')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'bucket'), name='uniq_alert_per_bucket')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'is_current', 'expiry_date'], name='compliance__company_b239bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('company', 'document_type', 'reference_name'), name='uniq_current_compliance_document', violation_error_message='This company already has a current document of this type with the same reference. Renew that one, or give this one a different reference name.'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('issue_date__isnull', True), ('expiry_date__gte', models.F('issue_date')), _connector='OR'), name='compliance_expiry_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='renewaltask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('document',), name='one_open_renewal_per_document', violation_error_message='A renewal is already open for this document.'),
        ),
    ]
