# Generated by Django 6.1.1 on 2026-10-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_current_compliance_document',
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Set for personal documents; empty for company documents.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_documents', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='renewalpayment',
            name='charged_to_employee',
            field=models.BooleanField(default=False, help_text='The employee bears this cost (payroll will deduct it once payroll exists).'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['employee', 'is_current'], name='compliance__employe_f3db87_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True), ('is_current', True)), fields=('company', 'document_type', 'reference_name'), name='uniq_current_company_document', violation_error_message='This company already has a current document of this type with the same reference. Renew that one, or give this one a different reference name.'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('is_current', True)), fields=('employee', 'document_type', 'reference_name'), name='uniq_current_employee_document', violation_error_message='This employee already has a current document of this type with the same reference. Renew that one, or give this one a different reference name.'),
        ),
    ]
