# Generated by Django 6.1.1 on 2026-10-06 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_remove_document_uniq_current_compliance_document_and_more'),
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='applies_to',
            field=models.CharField(choices=[('company', 'Company'), ('employee', 'Employee'), ('dependant', 'Dependant'), ('vehicle', 'Vehicle')], default='company', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('vehicle__isnull', True)), fields=('company', 'document_type', 'reference_name'), name='uniq_current_compliance_document', violation_error_message='<keep your existing message>'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('vehicle__isnull', False)), fields=('vehicle', 'document_type', 'reference_name'), name='uniq_current_vehicle_document', violation_error_message='This vehicle already has a current document of this type. Renew that one instead.'),
        ),
    ]
