# Generated by Django 6.1.1 on 2026-10-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    def link_vehicle_documents(apps, schema_editor):
        """Each plate typed into 'reference name' becomes a Vehicle; its documents are linked to it."""
        DocumentType = apps.get_model("compliance", "DocumentType")
        Document = apps.get_model("compliance", "Document")
        Vehicle = apps.get_model("vehicles", "Vehicle")

        types = list(DocumentType.objects.filter(code="vehicle-registration"))
        for t in types:
            t.applies_to = "vehicle"
            t.save(update_fields=["applies_to"])

        for doc in Document.objects.filter(document_type__in=types, vehicle__isnull=True).order_by("id"):
            plate = " ".join(doc.reference_name.upper().split()) or f"UNKNOWN-{doc.pk}"
            vehicle = Vehicle.objects.filter(company_id=doc.company_id, plate_number=plate).first()
            if vehicle is None:
                vehicle = Vehicle.objects.create(
                    company_id=doc.company_id, plate_number=plate, make="Unknown",
                    notes="Created automatically from an existing Vehicle Registration document. "
                          "Please complete the details.")
            doc.vehicle = vehicle
            doc.reference_name = ""
            doc.save(update_fields=["vehicle", "reference_name"])


    dependencies = [
        ('compliance', '0003_document_vehicle_alter_documenttype_applies_to_and_more'),
    ]

    operations = [migrations.RunPython(link_vehicle_documents, migrations.RunPython.noop)
    ]
