# Generated by Django 6.1.1 on 2026-10-06 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_link_vehicle_documents'),
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_current_company_document',
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_current_compliance_document',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', True), ('is_current', True), ('vehicle__isnull', True)), fields=('company', 'document_type', 'reference_name'), name='uniq_current_company_document', violation_error_message='This company already has a current document of this type with the same reference. Renew that one, or give this one a different reference name.'),
        ),
    ]
