# Generated by Django 6.1.1 on 2026-10-06 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('car', 'Car'), ('pickup', 'Pickup'), ('van', 'Van'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='car', max_length=12)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('chassis_number', models.CharField(blank=True, max_length=30, verbose_name='Chassis (VIN) number')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=10)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('loan', 'Bought with a loan'), ('leased', 'Leased')], default='owned', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('workshop', 'In workshop'), ('sold', 'Sold')], default='active', max_length=10)),
                ('odometer', models.PositiveIntegerField(default=0, verbose_name='Odometer (km)')),
                ('sold_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'plate_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'sold'), _negated=True), fields=('company', 'plate_number'), name='uniq_unsold_vehicle_plate', violation_error_message='This company already has an unsold vehicle with this plate number.'), models.UniqueConstraint(condition=models.Q(models.Q(('chassis_number', ''), _negated=True), models.Q(('status', 'sold'), _negated=True)), fields=('chassis_number',), name='uniq_unsold_vehicle_chassis', violation_error_message='A vehicle with this chassis number is already registered.'), models.CheckConstraint(condition=models.Q(('sold_on__isnull', False), models.Q(('status', 'sold'), _negated=True), _connector='OR'), name='vehicle_sold_has_date')],
            },
        ),
    ]
