# Generated by Django 6.1.1 on 2026-10-06 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_on', models.DateField()),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer (km)')),
                ('source', models.CharField(choices=[('initial', 'Entered when the vehicle was added'), ('manual', 'Manual entry'), ('assignment', 'Hand-over / return'), ('fuel', 'Fuel fill'), ('service', 'Service')], default='manual', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odometer_readings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-reading_on', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'reading_on'], name='vehicles_od_vehicle_156dba_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('start_odometer', models.PositiveIntegerField(verbose_name='Odometer at hand-over (km)')),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer at return (km)')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-assigned_from', '-id'],
                'indexes': [models.Index(fields=['employee', 'assigned_to'], name='vehicles_ve_employe_0652ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', True)), fields=('vehicle',), name='one_open_assignment_per_vehicle', violation_error_message='This vehicle is already assigned. Return it first.'), models.CheckConstraint(condition=models.Q(('assigned_to__isnull', True), ('assigned_to__gte', models.F('assigned_from')), _connector='OR'), name='assignment_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('end_odometer__isnull', True), ('end_odometer__gte', models.F('start_odometer')), _connector='OR'), name='assignment_end_km_not_below_start')],
            },
        ),
    ]
