# Generated by Django 6.1.1 on 2026-10-06 21:16

from django.db import migrations

def backfill(apps, schema_editor):
    """Vehicles added in phase 1 have an odometer but no readings; give each one a first reading."""
    Vehicle = apps.get_model("vehicles", "Vehicle")
    Reading = apps.get_model("vehicles", "OdometerReading")
    for v in Vehicle.objects.filter(odometer__gt=0, odometer_readings__isnull=True):
        Reading.objects.create(company_id=v.company_id, vehicle=v, reading_on=v.created_at.date(),
                               odometer=v.odometer, source="initial", note="Existing odometer value")

class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_odometerreading_vehicleassignment'),
    ]

    operations = [
        migrations.RunPython(backfill,migrations.RunPython.noop),
    ]
