# Generated by Django 6.1.1 on 2026-10-06 21:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0003_backfill_initial_odometer_readings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odometerreading',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='voided_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('every_km', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeat every (km)')),
                ('every_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeat every (months)')),
                ('warn_km', models.PositiveIntegerField(default=500, verbose_name='Warn when this many km are left')),
                ('warn_days', models.PositiveSmallIntegerField(default=30, verbose_name='Warn when this many days are left')),
                ('baseline_on', models.DateField(verbose_name='Last done on')),
                ('baseline_km', models.PositiveIntegerField(verbose_name='Last done at (km)')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_plans', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=8)),
                ('anchor', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.serviceplan')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled service'), ('repair', 'Repair'), ('other', 'Other work')], default='scheduled', max_length=10)),
                ('serviced_on', models.DateField()),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer (km)')),
                ('garage', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('parts_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parts (BHD)')),
                ('labour_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Labour (BHD)')),
                ('invoice_no', models.CharField(blank=True, max_length=40)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, related_name='records', to='vehicles.serviceplan')),
                ('reading', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicles.odometerreading')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-serviced_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_on', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total cost (BHD)')),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer (km)')),
                ('full_tank', models.BooleanField(default=True, help_text='Filled to the top. Needed to work out km per litre.')),
                ('station', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, editable=False, help_text='Whoever had the vehicle on that day, kept as it was then.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('reading', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vehicles.odometerreading')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_fills', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-filled_on', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'filled_on'], name='vehicles_fu_vehicle_a4e915_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('litres__gt', 0)), name='fuel_litres_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.CheckConstraint(condition=models.Q(('every_km__isnull', False), ('every_months__isnull', False), _connector='OR'), name='service_plan_has_an_interval'),
        ),
        migrations.AddConstraint(
            model_name='serviceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle', 'name'), name='uniq_active_service_plan_name', violation_error_message='This vehicle already has an active plan with this name.'),
        ),
        migrations.AddConstraint(
            model_name='planalertlog',
            constraint=models.UniqueConstraint(fields=('plan', 'state', 'anchor'), name='uniq_alert_per_plan_cycle'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['vehicle', 'serviced_on'], name='vehicles_se_vehicle_203d3c_idx'),
        ),
    ]
