# Generated by Django 6.1.1 on 2026-10-07 05:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0004_odometerreading_is_voided_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_on', models.DateField(verbose_name='Date of the accident')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(help_text='What happened, and what was damaged.')),
                ('police_report_no', models.CharField(blank=True, max_length=40, verbose_name='Police report number')),
                ('fault', models.CharField(choices=[('unknown', 'Not decided'), ('driver', 'Our driver'), ('other', 'Other party'), ('shared', 'Shared')], default='unknown', max_length=8)),
                ('injuries', models.BooleanField(default=False, help_text='Was anyone hurt?')),
                ('third_party', models.BooleanField(default=False, verbose_name='Another vehicle or person involved')),
                ('third_party_details', models.TextField(blank=True, help_text='Name, plate, phone and insurer of the other party.')),
                ('claim_status', models.CharField(choices=[('none', 'No claim'), ('filed', 'Claim filed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid out')], default='none', max_length=8, verbose_name='Insurance claim')),
                ('claim_no', models.CharField(blank=True, max_length=40, verbose_name='Claim number')),
                ('insurance_recovered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recovered from insurance (BHD)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_accidents', to='employees.employee')),
                ('repairs', models.ManyToManyField(blank=True, related_name='accidents', to='vehicles.servicerecord')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'occurred_on'], name='vehicles_ac_vehicle_be2a1d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'open'), ('closed_on__isnull', False), _connector='OR'), name='accident_closed_has_a_date')],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fined_on', models.DateField(verbose_name='Date of the offence')),
                ('reference', models.CharField(blank=True, max_length=40, verbose_name='Fine / ticket number')),
                ('offence', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (BHD)')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_reference', models.CharField(blank=True, max_length=60)),
                ('charged_to_employee', models.BooleanField(default=False, help_text='The driver bears this cost (payroll will deduct it once payroll exists).')),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fines', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-fined_on', '-id'],
                'permissions': [('pay_fine', 'Can record fine payments')],
                'indexes': [models.Index(fields=['vehicle', 'fined_on'], name='vehicles_fi_vehicle_e12c87_idx'), models.Index(fields=['status', 'is_voided'], name='vehicles_fi_status_d5a065_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fine_amount_positive'), models.CheckConstraint(condition=models.Q(('status', 'unpaid'), ('paid_on__isnull', False), _connector='OR'), name='fine_paid_has_a_date'), models.UniqueConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), ('is_voided', False)), fields=('vehicle', 'reference'), name='uniq_fine_reference_per_vehicle', violation_error_message='This fine is already recorded for this vehicle.')],
            },
        ),
    ]
