# Generated by Django 6.1.1 on 2026-10-07 09:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0005_accident_fine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.CharField(max_length=100, verbose_name='Bank / lender')),
                ('account_no', models.CharField(blank=True, max_length=60, verbose_name='Loan / account number')),
                ('down_payment', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Down payment (BHD)')),
                ('financed_amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount financed (BHD)')),
                ('installment_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Number of installments')),
                ('installment_amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installment (BHD)')),
                ('final_installment_amount', models.DecimalField(blank=True, decimal_places=3, help_text='Only if the last installment differs from the others.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Last installment (BHD)')),
                ('first_due_on', models.DateField(verbose_name='First installment due on')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Fully paid'), ('settled', 'Settled early')], default='active', max_length=10)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('settlement_reference', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_reason', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-first_due_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('due_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('settled', 'Cleared by early settlement')], default='due', max_length=7)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='vehicles.vehicleloan')),
            ],
            options={
                'ordering': ['loan', 'number'],
                'permissions': [('pay_loaninstallment', 'Can record loan installment payments')],
            },
        ),
        migrations.CreateModel(
            name='LoanAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=8)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.loaninstallment')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('installment', 'state'), name='uniq_alert_per_installment_state')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleloan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_voided', False), ('status', 'active')), fields=('vehicle',), name='one_active_loan_per_vehicle', violation_error_message='This vehicle already has an active loan.'),
        ),
        migrations.AddConstraint(
            model_name='vehicleloan',
            constraint=models.CheckConstraint(condition=models.Q(('financed_amount__gt', 0)), name='loan_financed_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicleloan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_amount__gt', 0)), name='loan_installment_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicleloan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'settled'), _negated=True), ('settled_on__isnull', False), _connector='OR'), name='loan_settled_has_a_date'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['status', 'due_on'], name='vehicles_lo_status_8683f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'number'), name='uniq_installment_number_per_loan'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_on__isnull', False), _connector='OR'), name='installment_paid_has_a_date'),
        ),
    ]
