# Generated by Django 6.1.1 on 2026-10-07 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_no_employeenumbersequence'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0006_vehicleloan_loaninstallment_loanalertlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('handover', 'Hand over to someone else'), ('keep', 'Keep with the employee'), ('return', 'Return to the company')], max_length=10)),
                ('planned_on', models.DateField(blank=True, help_text='For example the last working day. Only a plan: HR records the real date.', null=True, verbose_name='When')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaverAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='fine',
            name='recovered_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fine',
            name='recovered_on',
            field=models.DateField(blank=True, help_text='When the driver paid the company back.', null=True),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(('recovered_on__isnull', True), ('charged_to_employee', True), _connector='OR'), name='fine_recovered_only_if_charged'),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_requests', to='vehicles.vehicleassignment'),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='employee',
            field=models.ForeignKey(help_text='The person holding the vehicle.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_custody_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='new_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodyrequest',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_requests', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='leaveralertlog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaver_alerts', to='vehicles.vehicleassignment'),
        ),
        migrations.AddConstraint(
            model_name='custodyrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('assignment',), name='one_pending_custody_request_per_assignment', violation_error_message='A decision for this vehicle is already waiting for approval.'),
        ),
        migrations.AddConstraint(
            model_name='leaveralertlog',
            constraint=models.UniqueConstraint(fields=('assignment', 'state'), name='uniq_leaver_alert_per_state'),
        ),
    ]
