# Generated by Django 6.1.1 on 2026-10-07 11:17

import apps.compliance.storage
import apps.compliance.validators
import apps.vehicles.files
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('vehicles', '0007_custodyrequest_leaveralertlog_fine_recovered_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.fine')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('fine', 'week'), name='uniq_fine_reminder_per_week')],
            },
        ),
        migrations.CreateModel(
            name='VehicleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('ticket', 'Fine ticket'), ('police_report', 'Police report'), ('photo', 'Photo'), ('contract', 'Loan contract'), ('statement', 'Loan statement'), ('other', 'Other')], default='other', max_length=14)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(max_length=200, storage=apps.compliance.storage.private_storage, upload_to=apps.vehicles.files.vehicle_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.compliance.validators.validate_file_size])),
                ('is_removed', models.BooleanField(default=False)),
                ('removed_reason', models.CharField(blank=True, max_length=200)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.accident')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.fine')),
                ('fuel_fill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.fuelfill')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.vehicleloan')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.servicerecord')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('accident__isnull', True), ('fine__isnull', True), ('fuel_fill__isnull', False), ('loan__isnull', True), ('service_record__isnull', True)), models.Q(('accident__isnull', True), ('fine__isnull', True), ('fuel_fill__isnull', True), ('loan__isnull', True), ('service_record__isnull', False)), models.Q(('accident__isnull', True), ('fine__isnull', False), ('fuel_fill__isnull', True), ('loan__isnull', True), ('service_record__isnull', True)), models.Q(('accident__isnull', False), ('fine__isnull', True), ('fuel_fill__isnull', True), ('loan__isnull', True), ('service_record__isnull', True)), models.Q(('accident__isnull', True), ('fine__isnull', True), ('fuel_fill__isnull', True), ('loan__isnull', False), ('service_record__isnull', True)), _connector='OR'), name='vehicle_file_has_exactly_one_owner')],
            },
        ),
    ]
