# Generated by Django 6.1.1 on 2026-10-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=80, verbose_name='Name (Arabic)')),
                ('is_paid', models.BooleanField(default=True)),
                ('tracks_balance', models.BooleanField(default=False, help_text='Enforce a balance. Off = unlimited, HR monitors')),
                ('annual_entitlement', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('exclude_holidays', models.BooleanField(default=True, help_text='Public holidays inside the range are not charged')),
                ('exclude_weekly_offs', models.BooleanField(default=False, help_text='Weekly offs inside the range are not charged')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_types', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='leave/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
                'permissions': [('cancel_any_leave', 'Can cancel any approved leave')],
            },
        ),
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('entitlement', 'Entitlement'), ('carry_forward', 'Carry Forward'), ('taken', 'Taken'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=15)),
                ('days', models.DecimalField(decimal_places=1, help_text='+ adds to the balance, - deducts', max_digits=6)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_ledger', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leave.leavetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_leave_type_code'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date'], name='leave_leave_employe_d5249a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company', 'status'], name='leave_leave_company_35e267_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='leaveledger',
            index=models.Index(fields=['employee', 'leave_type', 'year'], name='leave_leave_employe_ebd42f_idx'),
        ),
    ]
