# Generated by Django 6.1.1 on 2026-10-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.company'),
        ),
    ]
