# Generated by Django 6.1.1 on 2026-10-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empty = applies to every company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.company'),
        ),
    ]
