# Generated by Django 6.1.1 on 2026-10-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('requested_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly Off'), ('late_entry', 'Late Entry'), ('early_exit', 'Early Exit')], max_length=15)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly Off'), ('late_entry', 'Late Entry'), ('early_exit', 'Early Exit')], max_length=15)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_exit_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('bulk', 'Bulk'), ('leave', 'Leave'), ('system', 'System'), ('correction', 'Correction')], default='manual', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_locked', models.BooleanField(default=False, help_text='Set when the payroll period is closed')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
            },
        ),
    ]
