# Generated by Django 6.1.1 on 2026-10-04 15:18

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_repr', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('export', 'Export'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('permission_denied', 'Denied')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('subject_employee_id', models.BigIntegerField(blank=True, null=True)),
                ('subject_repr', models.CharField(blank=True, max_length=255)),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'Whatsapp'), ('system', 'System')], default='system', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_c1f818_idx'), models.Index(fields=['subject_employee_id', '-timestamp'], name='audit_audit_subject_30ca91_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_17d98a_idx'), models.Index(fields=['module', '-timestamp'], name='audit_audit_module_c20e9a_idx')],
            },
        ),
    ]
