# Generated by Django 6.1.1 on 2026-10-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_no', models.CharField(max_length=30)),
                ('worker_type', models.CharField(choices=[('staff', 'Staff'), ('labor', 'Labor')], default='staff', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_notice', 'On Notice'), ('separated', 'Separated')], default='active', max_length=10)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=160, verbose_name='Name (Arabic)')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('whatsapp_verified', models.BooleanField(default=False)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('contract', 'Contract')], default='permanent', max_length=10)),
                ('joining_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.designation')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.grade')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.location')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'employee_no'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('contract', 'Contract')], max_length=10)),
                ('reason', models.CharField(choices=[('joining', 'Joining'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('manager_change', 'Manager Change'), ('contract_change', 'Contract Change'), ('correction', 'Correction')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.grade')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.location')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_no'), name='uniq_employee_no_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='uniq_employee_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('employee',), name='one_open_record_per_employee'),
        ),
    ]
