# Generated by Django 6.1.1 on 2026-10-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['company', 'employee_no'], 'permissions': [('manage_logins', 'Can create and reset employee logins')]},
        ),
    ]
