# Generated by Django 6.1.1 on 2026-10-05 09:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options'),
        ('organization', '0002_alter_department_company_alter_department_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(blank=True, help_text='Assigned automatically when left blank.', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_type', models.CharField(choices=[('staff', 'Staff'), ('labor', 'Labor')], max_length=10)),
                ('prefix', models.CharField(blank=True, max_length=12)),
                ('padding', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('next_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'worker_type'), name='uniq_number_sequence')],
            },
        ),
    ]
